#!/bin/bash
# Generated by Cursor

set -e

# AI Status Indicators GNOME Extension Installation Script

EXTENSION_UUID="ai-status-indicators@jewzaam.github.io"
EXTENSION_DIR="$HOME/.local/share/gnome-shell/extensions/$EXTENSION_UUID"

echo "Installing AI Status Indicators GNOME Extension..."

# Create extension directory
mkdir -p "$EXTENSION_DIR"

# Copy extension files
cp metadata.json "$EXTENSION_DIR/"
cp extension.js "$EXTENSION_DIR/"
cp prefs.js "$EXTENSION_DIR/"
cp stylesheet.css "$EXTENSION_DIR/"

# Copy schemas
mkdir -p "$EXTENSION_DIR/schemas"
cp schemas/org.gnome.shell.extensions.ai-status-indicators.gschema.xml "$EXTENSION_DIR/schemas/"

# Compile schema
echo "Compiling GSettings schema..."
glib-compile-schemas "$EXTENSION_DIR/schemas/"

echo "Extension installed successfully!"
echo ""
echo "To enable the extension:"
echo "1. Restart GNOME Shell (Alt+F2, type 'r', press Enter)"
echo "2. Or log out and log back in"
echo "3. Enable the extension via Extensions app or command line:"
echo "   gnome-extensions enable $EXTENSION_UUID"
echo ""
echo "To configure the extension:"
echo "   gnome-extensions prefs $EXTENSION_UUID" 