#!/bin/bash
# Generated by Cursor

set -e

# AI Status Indicators GNOME Extension Uninstall Script

EXTENSION_UUID="ai-status-indicators@jewzaam.github.io"
EXTENSION_DIR="$HOME/.local/share/gnome-shell/extensions/$EXTENSION_UUID"

echo "Uninstalling AI Status Indicators GNOME Extension..."

# Check if extension directory exists
if [ ! -d "$EXTENSION_DIR" ]; then
    echo "Extension is not installed (directory not found: $EXTENSION_DIR)"
    exit 0
fi

# Disable the extension if it's currently enabled
echo "Disabling extension if enabled..."
if command -v gnome-extensions &> /dev/null; then
    if gnome-extensions list --enabled | grep -q "$EXTENSION_UUID"; then
        echo "Extension is currently enabled. Disabling..."
        gnome-extensions disable "$EXTENSION_UUID"
        echo "Extension disabled successfully."
    else
        echo "Extension is not currently enabled."
    fi
else
    echo "Warning: gnome-extensions command not found. You may need to disable the extension manually."
fi

# Remove extension directory
echo "Removing extension files..."
rm -rf "$EXTENSION_DIR"

echo "Extension uninstalled successfully!"
echo ""
echo "To complete the uninstallation:"
echo "1. Restart GNOME Shell (Alt+F2, type 'r', press Enter)"
echo "2. Or log out and log back in"
echo ""
echo "The extension has been completely removed from your system." 