name: PR Checks

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linter
      run: npm run lint
      
    - name: Run tests
      run: npm test
      
    - name: Generate coverage report
      run: npm run test:coverage
      
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage/lcov.info
        fail_ci_if_error: false
        
    - name: Test installation script
      run: |
        # Test that install.sh is executable and has correct extension UUID
        chmod +x install.sh
        if ! grep -q "ai-status-indicators@jewzaam.github.io" install.sh; then
          echo "Error: install.sh does not contain correct extension UUID"
          exit 1
        fi
        echo "✓ install.sh validation passed"
        
    - name: Test uninstall script
      run: |
        # Test that uninstall.sh is executable and has correct extension UUID
        chmod +x uninstall.sh
        if ! grep -q "ai-status-indicators@jewzaam.github.io" uninstall.sh; then
          echo "Error: uninstall.sh does not contain correct extension UUID"
          exit 1
        fi
        echo "✓ uninstall.sh validation passed"
        
    - name: Validate metadata
      run: |
        # Check that metadata.json contains correct UUID
        if ! grep -q "ai-status-indicators@jewzaam.github.io" metadata.json; then
          echo "Error: metadata.json does not contain correct extension UUID"
          exit 1
        fi
        echo "✓ metadata.json validation passed" 